// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcks0saOvFb3Fnp8Cyo5YLONJ9qy7t_fQ',
    appId: '1:39442006147:web:3a9273b2b798dc41529bb6',
    messagingSenderId: '39442006147',
    projectId: 'koraa-5afaa',
    authDomain: 'koraa-5afaa.firebaseapp.com',
    storageBucket: 'koraa-5afaa.firebasestorage.app',
    measurementId: 'G-TGCQ48Z0H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOHRiMtMGyfne5U9-NO7fcmKFTxKd1iRg',
    appId: '1:39442006147:android:526e64a7a2c9038e529bb6',
    messagingSenderId: '39442006147',
    projectId: 'koraa-5afaa',
    storageBucket: 'koraa-5afaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZOx-3lbOifETN7m5Eis--OfJ6N6Ymm3M',
    appId: '1:39442006147:ios:c0ea11083810075e529bb6',
    messagingSenderId: '39442006147',
    projectId: 'koraa-5afaa',
    storageBucket: 'koraa-5afaa.firebasestorage.app',
    iosBundleId: 'com.example.korrrrrrrr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZOx-3lbOifETN7m5Eis--OfJ6N6Ymm3M',
    appId: '1:39442006147:ios:c0ea11083810075e529bb6',
    messagingSenderId: '39442006147',
    projectId: 'koraa-5afaa',
    storageBucket: 'koraa-5afaa.firebasestorage.app',
    iosBundleId: 'com.example.korrrrrrrr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcks0saOvFb3Fnp8Cyo5YLONJ9qy7t_fQ',
    appId: '1:39442006147:web:1889a9b318110d9d529bb6',
    messagingSenderId: '39442006147',
    projectId: 'koraa-5afaa',
    authDomain: 'koraa-5afaa.firebaseapp.com',
    storageBucket: 'koraa-5afaa.firebasestorage.app',
    measurementId: 'G-YMWP4KXFGQ',
  );
}
